"""Initial version

Revision ID: e36474addadc
Revises: 
Create Date: 2020-11-10 22:39:27.941666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e36474addadc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reporting_entity',
    sa.Column('id', sa.String(length=1000), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=False),
    sa.Column('primary_display', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('osm_id', sa.String(), nullable=True),
    sa.Column('centerpoint', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('org', sa.String(length=1000), nullable=True),
    sa.Column('user_type', sa.String(length=1000), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('admin', sa.String(length=100), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.Column('confirmed', sa.String(length=100), nullable=True),
    sa.Column('confirmed_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('entity_property',
    sa.Column('id', sa.String(length=1000), nullable=False),
    sa.Column('property', sa.String(length=1000), nullable=False),
    sa.Column('is_numeric', sa.Boolean(), nullable=False),
    sa.Column('numb_value', sa.Float(), nullable=True),
    sa.Column('str_value', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['reporting_entity.id'], ),
    sa.PrimaryKeyConstraint('id', 'property')
    )
    op.create_table('entity_to_subentity',
    sa.Column('entity_id', sa.String(length=1000), nullable=False),
    sa.Column('subentity_id', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['reporting_entity.id'], ),
    sa.ForeignKeyConstraint(['subentity_id'], ['reporting_entity.id'], ),
    sa.PrimaryKeyConstraint('entity_id', 'subentity_id')
    )
    op.create_table('super_user',
    sa.Column('superuser_id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['superuser_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('superuser_id')
    )
    op.create_table('user_to_entity',
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=1000), nullable=False),
    sa.Column('role', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['reporting_entity.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'entity_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_to_entity')
    op.drop_table('super_user')
    op.drop_table('entity_to_subentity')
    op.drop_table('entity_property')
    op.drop_table('user')
    op.drop_table('reporting_entity')
    # ### end Alembic commands ###
